config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  resources :topics
  resources :questions
  resources :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, :optional => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :topic, :optional => true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions
  has_many :answers, :through => :questions
end

# Do we need ActiveRecord::Base here??? No it is from application_record.rb

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
    # render json: @answers
  end

  def new
    @answer = Answer.new
    # render json: @answer
  end

  def create
    answer = Answer.create answer_params
    redirect_to answer
    # render json: answer
  end

  def edit
  end

  def show
    @answer = Answer.find params[:id]
    render json: @answers
  end

  def destroy
    answer = Answer.find params[:id]
    answer.destroy
    redirect_to question_path
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :topic_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token #required for APIs
end

# do we need to inherit from ActiveRecord ????

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    # render json: @questions
  end

  def new
    @question = Question.new
    # render json: @question
  end

  def create
    question = Question.create question_params
    redirect_to question
    # render json: question
  end

  def edit
  end

  def update
    question = Question.find params[:id]
    question.update question_params
    redirect_to question
  end

  def show
    @question = Question.find params[:id]
    # render json: @questions
  end

  def destroy
    question = Question.find params[:id]
    question.destroy
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:content, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    # render json: @topics
  end
  #
  def new
    @topic = Topic.new
    # render json: @topic
  end
  #
  def create
    topic = Topic.create topic_params
    redirect_to topic_path(topic.id) #show page
    # render json: topic
  end
  #
  def edit
    @topic = Topic.find params[:id]
    # render json: @topic
  end
  #
  def update
    topic = Topic.find params[:id]
    topic.update topic_params
    redirect_to topic
    # render json: topic
  end
  #
  def show
    @topic = Topic.find params[:id]
    # render :show
      render json: @topic, :include => {:questions => {:include => :answers}}
  end
  #
  def destroy
    topic = Topic.find params[:id]
    topic.destroy
    redirect_to topics_path
    # head :no_content, status: :ok
  end


  private
  def topic_params
    params.require(:topic).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/answers/edit.html.erb
<h1>Edit Questions</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>All Answers</h1>

<% @answers.each do |answer| %>
  <%= link_to answer.content, answer %>
<% end %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= form_for @answer do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/answers/show.html.erb
<h1>Answers</h1>

<p><%= @answer.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizAppRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'All topics', topics_path %>
      <%= link_to 'New topic', new_topic_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<h2><%= link_to 'Pick a topic', topics_path %></h2>

app/views/questions/index.html.erb
<h1>Question Bank</h1>

<% @questions.each do |question| %>
  <%= link_to question.content, question %>
<% end %>

app/views/questions/new.html.erb
<h1>Create New Question</h1>

<%= form_for @question do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.topic.title %></h1>

<h2><%= @question.content %></h2>

<% @question.answers.each do |answer| %>
  <%= link_to answer.content, answer %>
<% end %>

<p>Answers coming soon</p>
<ul>
  <li>Choice 1</li>
  <li>Choice 2</li>
  <li>Choice 3</li>
  <li>Choice 4</li>
</ul>



<div class="controls">
  <%= link_to 'Edit Question', edit_question_path(@question) %>
  <%= button_to 'Delete Question', @question, :method => 'delete' %>
  <%= link_to 'All Questions', questions_path %>

app/views/topics/edit.html.erb
<h1>Edit Quiz Topic</h1>
<%= form_for @topic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit %>
<% end %>

app/views/topics/index.html.erb
<h1>All Quiz Topics</h1>

<% @topics.each do |topic| %>
  <ul>
    <li><%= link_to topic.title, topic_path(topic.id) %></li>
  </ul>
  <p><%= image_tag topic.image, :class => 'thumb' %></p>
<% end %>

app/views/topics/new.html.erb
<h1>New Quiz Topic</h1>

<%= form_for @topic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.submit %>
<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<% @topic.questions.each do |question| %>
<p><%= question.content %></p>
<% question.answers.each do | a | %>
 <%= a.content %>
 <% end %>
<% end %>

<p>Questions coming soon</p>

<p> Answers coming soon<p>


  <div class="controls">
    <%= link_to 'Edit Topic', edit_topic_path(@topic) %>
    <%= button_to 'Delete Topic', @topic, :method => 'delete' %>

  </div>